// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(PalitaxDbContext))]
    [Migration("20220109151451_seed database")]
    partial class seeddatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "US",
                            FullName = "Bruno Mars",
                            State = "NY",
                            ZipCode = "10118"
                        },
                        new
                        {
                            Id = 2,
                            Country = "CA",
                            FullName = "Jim Carrey",
                            State = "BC",
                            ZipCode = "V6G 3E2"
                        },
                        new
                        {
                            Id = 3,
                            Country = "FR",
                            FullName = "Thierry Henry",
                            ZipCode = "75008"
                        },
                        new
                        {
                            Id = 4,
                            Country = "AU",
                            FullName = "Nicole Kidman",
                            ZipCode = "NSW 2000"
                        },
                        new
                        {
                            Id = 5,
                            Country = "CA",
                            FullName = "Carey Price",
                            State = "QC",
                            ZipCode = "H3G 0B7"
                        },
                        new
                        {
                            Id = 6,
                            Country = "FR",
                            FullName = "Jean Reno",
                            ZipCode = "13281"
                        },
                        new
                        {
                            Id = 7,
                            Country = "AU",
                            FullName = "Mel Gibson",
                            ZipCode = "VIC 3002"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hand Sanitizer",
                            Price = 13.95f
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dell p2419h Monitor",
                            Price = 449.99f
                        },
                        new
                        {
                            Id = 3,
                            Description = "Delonghi Dedica Coffee Machine",
                            Price = 269.99f
                        },
                        new
                        {
                            Id = 4,
                            Description = "Logitech MX Master 3 Mouse",
                            Price = 129.99f
                        },
                        new
                        {
                            Id = 5,
                            Description = "BlackVue DR900X-2CH Plus DASH​CAM",
                            Price = 489.99f
                        },
                        new
                        {
                            Id = 6,
                            Description = "Arduino Uno Rev3",
                            Price = 23f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
